list = [ ]
a=int(input("enter marks of the student"))
list.append(a)
b=int(input("enter marks of the student"))
list.append(b)
c=int(input("enter marks of the student"))
list.append(c)
d=int(input("enter marks of the student"))
list.append(d)
e=int(input("enter marks of the student"))
list.append(e)
f=int(input("enter marks of the student"))
list.append(f)
g=int(input("enter marks of the student"))
list.append(g)
list.sort()
print(list)
